### ISSUE TITLE
Please, capitalize the first letter of every word in labels.

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_SecuritySuiteCommon#3]
Please, capitalize the first letter of every word in labels.

https://github.com/magento/magespecialist_SecuritySuiteCommon/blob/bdfead448f49cc6c6119d2034aec438b730ce7ab/etc/adminhtml/system.xml#L33

https://github.com/magento/magespecialist_SecuritySuiteCommon/blob/bdfead448f49cc6c6119d2034aec438b730ce7ab/etc/adminhtml/system.xml#L42

**Comment by TomashKhamlai** [comment]
What is the purpose of the 'Stealth Mode' and how it works? I checked the documentation that is available on GitHub but haven't found anything useful for me. Please, explain.

**Comment by phoenix128** [comment]
Ignore it, it has been removed in this PR:
https://github.com/magento/magespecialist_SecuritySuiteCommon/pull/4

It was a feature for other components in the security suite, but we decided to remove it.

**Comment by TomashKhamlai** [comment]
https://github.com/magento/magespecialist_SecuritySuiteCommon/pull/4/files#r176057854
